Th2 1570
th2-net/th2-conn-generic pull request #8
Opened 2021-03-02 17:20 UTC by Nikita-Smirnov-Exactpro

2021-03-02 17:23 UTC, OptimumOpium approved these changes

2021-03-02 17:23 UTC, OptimumOpium commented on README.md
> +  + Copy parent event id from incoming th2 message to the outgoing th2 message after sending
```suggestion
  + Copies a parent event id from the incoming th2 message after it is sent to the outgoing th2 message
```

2021-03-03 08:30 UTC, jean-michel-perli-sonsin commented on README.md
>  Each connect can support several service types and each one can have its own parameters to configure.
Each **connect extension** can support several service types and each one can have its own parameters to configure.

2021-03-03 08:31 UTC, jean-michel-perli-sonsin requested changes
Hi, I just add one comment for this file. Please see if you agree with it and correct it.
Thanks!

2021-03-03 10:30 UTC, OptimumOpium approved these changes

2021-03-03 10:31 UTC, merged